# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='process.proto',
  package='uart',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rprocess.proto\x12\x04uart\x1a\x0c\x63ommon.proto\"2\n\rStartStop_req\x12!\n\x03\x63md\x18\x01 \x01(\x0e\x32\x14.uart.startstop_enum\"?\n\x0cSteering_req\x12 \n\x03\x63md\x18\x01 \x01(\x0e\x32\x13.uart.steering_enum\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\"%\n\x0cThrottle_req\x12\x15\n\rthrottleValue\x18\x01 \x01(\r\"\x1f\n\tBrake_req\x12\x12\n\nbrakeValue\x18\x01 \x01(\x08\"4\n\x0cStateWorking\x12$\n\x03\x63md\x18\x01 \x01(\x0e\x32\x17.uart.stateWorking_enum\"\x19\n\x05HCSR4\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\"*\n\x03GPS\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"\xc4\x02\n\x07pub_sub\x12\'\n\x08msg_type\x18\x01 \x01(\x0e\x32\x15.uart.pub_sub_message\x12(\n\tstartstop\x18\x02 \x01(\x0b\x32\x13.uart.StartStop_reqH\x00\x12&\n\x08throttle\x18\x03 \x01(\x0b\x32\x12.uart.Throttle_reqH\x00\x12&\n\x08steering\x18\x04 \x01(\x0b\x32\x12.uart.Steering_reqH\x00\x12 \n\x05\x62rake\x18\x05 \x01(\x0b\x32\x0f.uart.Brake_reqH\x00\x12\'\n\tstatework\x18\x06 \x01(\x0b\x32\x12.uart.StateWorkingH\x00\x12 \n\thcsr4_dis\x18\x07 \x01(\x0b\x32\x0b.uart.HCSR4H\x00\x12\x1d\n\x08location\x18\x08 \x01(\x0b\x32\t.uart.GPSH\x00\x42\n\n\x08messages*%\n\x0estartstop_enum\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01*$\n\rsteering_enum\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01*8\n\x11stateWorking_enum\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\x0c\n\x08INACTIVE\x10\x01\x12\t\n\x05\x45RROR\x10\x02*\x8b\x01\n\x0fpub_sub_message\x12\x12\n\x0eSTART_STOP_MSG\x10\x00\x12\x10\n\x0cTHROTTLE_MSG\x10\x01\x12\x10\n\x0cSTEERING_MSG\x10\x02\x12\r\n\tBRAKE_MSG\x10\x03\x12\x15\n\x11STATE_WORKING_MSG\x10\x04\x12\r\n\tHCSR4_MSG\x10\x05\x12\x0b\n\x07GPS_MSG\x10\x06\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_STARTSTOP_ENUM = _descriptor.EnumDescriptor(
  name='startstop_enum',
  full_name='uart.startstop_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=678,
  serialized_end=715,
)
_sym_db.RegisterEnumDescriptor(_STARTSTOP_ENUM)

startstop_enum = enum_type_wrapper.EnumTypeWrapper(_STARTSTOP_ENUM)
_STEERING_ENUM = _descriptor.EnumDescriptor(
  name='steering_enum',
  full_name='uart.steering_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=717,
  serialized_end=753,
)
_sym_db.RegisterEnumDescriptor(_STEERING_ENUM)

steering_enum = enum_type_wrapper.EnumTypeWrapper(_STEERING_ENUM)
_STATEWORKING_ENUM = _descriptor.EnumDescriptor(
  name='stateWorking_enum',
  full_name='uart.stateWorking_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=755,
  serialized_end=811,
)
_sym_db.RegisterEnumDescriptor(_STATEWORKING_ENUM)

stateWorking_enum = enum_type_wrapper.EnumTypeWrapper(_STATEWORKING_ENUM)
_PUB_SUB_MESSAGE = _descriptor.EnumDescriptor(
  name='pub_sub_message',
  full_name='uart.pub_sub_message',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START_STOP_MSG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROTTLE_MSG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEERING_MSG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAKE_MSG', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_WORKING_MSG', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HCSR4_MSG', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_MSG', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=814,
  serialized_end=953,
)
_sym_db.RegisterEnumDescriptor(_PUB_SUB_MESSAGE)

pub_sub_message = enum_type_wrapper.EnumTypeWrapper(_PUB_SUB_MESSAGE)
START = 0
STOP = 1
LEFT = 0
RIGHT = 1
ACTIVE = 0
INACTIVE = 1
ERROR = 2
START_STOP_MSG = 0
THROTTLE_MSG = 1
STEERING_MSG = 2
BRAKE_MSG = 3
STATE_WORKING_MSG = 4
HCSR4_MSG = 5
GPS_MSG = 6



_STARTSTOP_REQ = _descriptor.Descriptor(
  name='StartStop_req',
  full_name='uart.StartStop_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='uart.StartStop_req.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=87,
)


_STEERING_REQ = _descriptor.Descriptor(
  name='Steering_req',
  full_name='uart.Steering_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='uart.Steering_req.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='uart.Steering_req.angle', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=152,
)


_THROTTLE_REQ = _descriptor.Descriptor(
  name='Throttle_req',
  full_name='uart.Throttle_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='throttleValue', full_name='uart.Throttle_req.throttleValue', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=191,
)


_BRAKE_REQ = _descriptor.Descriptor(
  name='Brake_req',
  full_name='uart.Brake_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='brakeValue', full_name='uart.Brake_req.brakeValue', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=224,
)


_STATEWORKING = _descriptor.Descriptor(
  name='StateWorking',
  full_name='uart.StateWorking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='uart.StateWorking.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=278,
)


_HCSR4 = _descriptor.Descriptor(
  name='HCSR4',
  full_name='uart.HCSR4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='uart.HCSR4.distance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=305,
)


_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='uart.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='uart.GPS.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='uart.GPS.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=349,
)


_PUB_SUB = _descriptor.Descriptor(
  name='pub_sub',
  full_name='uart.pub_sub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='uart.pub_sub.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startstop', full_name='uart.pub_sub.startstop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='uart.pub_sub.throttle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering', full_name='uart.pub_sub.steering', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake', full_name='uart.pub_sub.brake', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statework', full_name='uart.pub_sub.statework', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hcsr4_dis', full_name='uart.pub_sub.hcsr4_dis', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='uart.pub_sub.location', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='messages', full_name='uart.pub_sub.messages',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=352,
  serialized_end=676,
)

_STARTSTOP_REQ.fields_by_name['cmd'].enum_type = _STARTSTOP_ENUM
_STEERING_REQ.fields_by_name['cmd'].enum_type = _STEERING_ENUM
_STATEWORKING.fields_by_name['cmd'].enum_type = _STATEWORKING_ENUM
_PUB_SUB.fields_by_name['msg_type'].enum_type = _PUB_SUB_MESSAGE
_PUB_SUB.fields_by_name['startstop'].message_type = _STARTSTOP_REQ
_PUB_SUB.fields_by_name['throttle'].message_type = _THROTTLE_REQ
_PUB_SUB.fields_by_name['steering'].message_type = _STEERING_REQ
_PUB_SUB.fields_by_name['brake'].message_type = _BRAKE_REQ
_PUB_SUB.fields_by_name['statework'].message_type = _STATEWORKING
_PUB_SUB.fields_by_name['hcsr4_dis'].message_type = _HCSR4
_PUB_SUB.fields_by_name['location'].message_type = _GPS
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['startstop'])
_PUB_SUB.fields_by_name['startstop'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['throttle'])
_PUB_SUB.fields_by_name['throttle'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['steering'])
_PUB_SUB.fields_by_name['steering'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['brake'])
_PUB_SUB.fields_by_name['brake'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['statework'])
_PUB_SUB.fields_by_name['statework'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['hcsr4_dis'])
_PUB_SUB.fields_by_name['hcsr4_dis'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
_PUB_SUB.oneofs_by_name['messages'].fields.append(
  _PUB_SUB.fields_by_name['location'])
_PUB_SUB.fields_by_name['location'].containing_oneof = _PUB_SUB.oneofs_by_name['messages']
DESCRIPTOR.message_types_by_name['StartStop_req'] = _STARTSTOP_REQ
DESCRIPTOR.message_types_by_name['Steering_req'] = _STEERING_REQ
DESCRIPTOR.message_types_by_name['Throttle_req'] = _THROTTLE_REQ
DESCRIPTOR.message_types_by_name['Brake_req'] = _BRAKE_REQ
DESCRIPTOR.message_types_by_name['StateWorking'] = _STATEWORKING
DESCRIPTOR.message_types_by_name['HCSR4'] = _HCSR4
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
DESCRIPTOR.message_types_by_name['pub_sub'] = _PUB_SUB
DESCRIPTOR.enum_types_by_name['startstop_enum'] = _STARTSTOP_ENUM
DESCRIPTOR.enum_types_by_name['steering_enum'] = _STEERING_ENUM
DESCRIPTOR.enum_types_by_name['stateWorking_enum'] = _STATEWORKING_ENUM
DESCRIPTOR.enum_types_by_name['pub_sub_message'] = _PUB_SUB_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartStop_req = _reflection.GeneratedProtocolMessageType('StartStop_req', (_message.Message,), {
  'DESCRIPTOR' : _STARTSTOP_REQ,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.StartStop_req)
  })
_sym_db.RegisterMessage(StartStop_req)

Steering_req = _reflection.GeneratedProtocolMessageType('Steering_req', (_message.Message,), {
  'DESCRIPTOR' : _STEERING_REQ,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.Steering_req)
  })
_sym_db.RegisterMessage(Steering_req)

Throttle_req = _reflection.GeneratedProtocolMessageType('Throttle_req', (_message.Message,), {
  'DESCRIPTOR' : _THROTTLE_REQ,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.Throttle_req)
  })
_sym_db.RegisterMessage(Throttle_req)

Brake_req = _reflection.GeneratedProtocolMessageType('Brake_req', (_message.Message,), {
  'DESCRIPTOR' : _BRAKE_REQ,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.Brake_req)
  })
_sym_db.RegisterMessage(Brake_req)

StateWorking = _reflection.GeneratedProtocolMessageType('StateWorking', (_message.Message,), {
  'DESCRIPTOR' : _STATEWORKING,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.StateWorking)
  })
_sym_db.RegisterMessage(StateWorking)

HCSR4 = _reflection.GeneratedProtocolMessageType('HCSR4', (_message.Message,), {
  'DESCRIPTOR' : _HCSR4,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.HCSR4)
  })
_sym_db.RegisterMessage(HCSR4)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), {
  'DESCRIPTOR' : _GPS,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.GPS)
  })
_sym_db.RegisterMessage(GPS)

pub_sub = _reflection.GeneratedProtocolMessageType('pub_sub', (_message.Message,), {
  'DESCRIPTOR' : _PUB_SUB,
  '__module__' : 'process_pb2'
  # @@protoc_insertion_point(class_scope:uart.pub_sub)
  })
_sym_db.RegisterMessage(pub_sub)


# @@protoc_insertion_point(module_scope)
