# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station_car.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='station_car.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11station_car.proto\x1a\x0c\x63ommon.proto\"%\n\x0b\x43ommand_req\x12\x16\n\x03\x63md\x18\x01 \x01(\x0e\x32\t.cmd_enum\"*\n\x0b\x43ommand_rep\x12\x1b\n\x06retVal\x18\x01 \x01(\x0e\x32\x0b.ReturnCode\"P\n\x08\x43ommands\x12\x1b\n\x03req\x18\x01 \x01(\x0b\x32\x0c.Command_reqH\x00\x12\x1b\n\x03rep\x18\x02 \x01(\x0b\x32\x0c.Command_repH\x00\x42\n\n\x08messages\"7\n\x0bseq_req_rep\x12\x1c\n\x07\x63md_msg\x18\x01 \x01(\x0b\x32\t.CommandsH\x00\x42\n\n\x08messages*\x1f\n\x08\x63md_enum\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_CMD_ENUM = _descriptor.EnumDescriptor(
  name='cmd_enum',
  full_name='cmd_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=288,
)
_sym_db.RegisterEnumDescriptor(_CMD_ENUM)

cmd_enum = enum_type_wrapper.EnumTypeWrapper(_CMD_ENUM)
START = 0
STOP = 1



_COMMAND_REQ = _descriptor.Descriptor(
  name='Command_req',
  full_name='Command_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='Command_req.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_COMMAND_REP = _descriptor.Descriptor(
  name='Command_rep',
  full_name='Command_rep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retVal', full_name='Command_rep.retVal', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=116,
)


_COMMANDS = _descriptor.Descriptor(
  name='Commands',
  full_name='Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='Commands.req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rep', full_name='Commands.rep', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='messages', full_name='Commands.messages',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=118,
  serialized_end=198,
)


_SEQ_REQ_REP = _descriptor.Descriptor(
  name='seq_req_rep',
  full_name='seq_req_rep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_msg', full_name='seq_req_rep.cmd_msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='messages', full_name='seq_req_rep.messages',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=200,
  serialized_end=255,
)

_COMMAND_REQ.fields_by_name['cmd'].enum_type = _CMD_ENUM
_COMMAND_REP.fields_by_name['retVal'].enum_type = common__pb2._RETURNCODE
_COMMANDS.fields_by_name['req'].message_type = _COMMAND_REQ
_COMMANDS.fields_by_name['rep'].message_type = _COMMAND_REP
_COMMANDS.oneofs_by_name['messages'].fields.append(
  _COMMANDS.fields_by_name['req'])
_COMMANDS.fields_by_name['req'].containing_oneof = _COMMANDS.oneofs_by_name['messages']
_COMMANDS.oneofs_by_name['messages'].fields.append(
  _COMMANDS.fields_by_name['rep'])
_COMMANDS.fields_by_name['rep'].containing_oneof = _COMMANDS.oneofs_by_name['messages']
_SEQ_REQ_REP.fields_by_name['cmd_msg'].message_type = _COMMANDS
_SEQ_REQ_REP.oneofs_by_name['messages'].fields.append(
  _SEQ_REQ_REP.fields_by_name['cmd_msg'])
_SEQ_REQ_REP.fields_by_name['cmd_msg'].containing_oneof = _SEQ_REQ_REP.oneofs_by_name['messages']
DESCRIPTOR.message_types_by_name['Command_req'] = _COMMAND_REQ
DESCRIPTOR.message_types_by_name['Command_rep'] = _COMMAND_REP
DESCRIPTOR.message_types_by_name['Commands'] = _COMMANDS
DESCRIPTOR.message_types_by_name['seq_req_rep'] = _SEQ_REQ_REP
DESCRIPTOR.enum_types_by_name['cmd_enum'] = _CMD_ENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_req = _reflection.GeneratedProtocolMessageType('Command_req', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_REQ,
  '__module__' : 'station_car_pb2'
  # @@protoc_insertion_point(class_scope:Command_req)
  })
_sym_db.RegisterMessage(Command_req)

Command_rep = _reflection.GeneratedProtocolMessageType('Command_rep', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_REP,
  '__module__' : 'station_car_pb2'
  # @@protoc_insertion_point(class_scope:Command_rep)
  })
_sym_db.RegisterMessage(Command_rep)

Commands = _reflection.GeneratedProtocolMessageType('Commands', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDS,
  '__module__' : 'station_car_pb2'
  # @@protoc_insertion_point(class_scope:Commands)
  })
_sym_db.RegisterMessage(Commands)

seq_req_rep = _reflection.GeneratedProtocolMessageType('seq_req_rep', (_message.Message,), {
  'DESCRIPTOR' : _SEQ_REQ_REP,
  '__module__' : 'station_car_pb2'
  # @@protoc_insertion_point(class_scope:seq_req_rep)
  })
_sym_db.RegisterMessage(seq_req_rep)


# @@protoc_insertion_point(module_scope)
